#自动调用api保活，加密版
name: Auto Renew O365 E5

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "12 */6 * * 1-5"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.event.repository.owner.id == github.event.sender.id  # 自己点start运行
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Python
      run: echo "{python}={v1}" >> $GITHUB_OUTPUT
#   旧版Github代码
#    - name: Setup Python
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Read config from secrets
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: | 
        cp config.py temp.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '4 r configid.txt' temp.py
        sed -i '6 r configkey.txt' temp.py
    - name: Test Api
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python temp.py
    - name: Delete secrets config
      run: | 
        rm -f temp.py
        rm -f configid.txt
        rm -f configkey.txt    
    - name: Commit 
      run: |
        git config --global user.email auvandy@hotmail.com
        git config --global user.name autorenew
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
